"""Initial migration

Revision ID: 1c33cb9b1e91
Revises: 
Create Date: 2026-02-23 14:01:36.285670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c33cb9b1e91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('writing_style', sa.JSON(), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('voice_description', sa.Text(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('built_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=500), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('is_own_content', sa.Boolean(), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovered_contents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timeframe', sa.String(length=100), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('counterarguments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contents')
    op.drop_table('topic_recommendations')
    op.drop_table('predictions')
    op.drop_table('discovered_contents')
    op.drop_table('content_sources')
    op.drop_table('author_profiles')
    # ### end Alembic commands ###
